In [7]:
import pandas as pd
pd.set_option("display.max_columns", None)

df_1 = pd.read_csv("../../../archive/with_rates_and_spec_gods.csv")
df_2 = pd.read_csv("../../../archive/2021_LoL_esports_match_data_from_SpinelessCoward_20210713.csv")

In [26]:
df_1.rename(columns = {"blueChamps": "blueChampions", "redChamps": "redChampions", "redKills": "blueDeaths",
                      "blueHas62": "blueHasWukong", "redHas62": "redHasWukong", "blueHas111": "blueHasNautilus",
                      "redHas111": "redHasNautilus", "blueHas145": "blueHasKaiSa", "redHas145": "redHasKaisa",
                      "blueHas39": "blueHasIrelia", "redHas39": "redHasIrelia", "blueHas517": "blueHasSylas",
                      "redHas517": "redHasSylas"}, inplace = True)

In [27]:
df_1.head()

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueAssists,blueDragons,blueHeralds,blueTowersDestroyed,blueAvgLevel,blueTotalExperience,blueTotalJungleMinionsKilled,blueGoldDiff,blueExperienceDiff,blueCSPerMin,blueGoldPerMin,redWardsPlaced,redWardsDestroyed,blueDeaths,redAssists,redDragons,redHeralds,redTowersDestroyed,redAvgLevel,redTotalExperience,redTotalJungleMinionsKilled,redCSPerMin,redGoldPerMin,blueChampions,redChampions,bluePredWinrate,redPredWinrate,blueAvgPickrate,redAvgPickrate,blueHasWukong,redHasWukong,blueHasNautilus,redHasNautilus,blueHasKaiSa,redHasKaisa,blueHasIrelia,redHasIrelia,blueHasSylas,redHasSylas
0,4519157822,0,28,2,1,9,11,0,0,0,6.6,17039,36,643,-8,19.5,1721.0,15,6,6,8,0,0,0,6.8,17047,55,19.7,1656.7,"[111, 91, 236, 76, 54]","[26, 235, 82, 421, 69]",0.489394,0.509859,0.086790,0.103614,False,False,True,False,False,False,False,False,False,False
1,4523371949,0,12,1,0,5,5,0,0,0,6.6,16265,43,-2908,-1173,17.4,1471.2,12,1,5,2,1,1,1,6.8,17438,52,24.0,1762.0,"[4, 350, 75, 145, 875]","[110, 59, 53, 134, 39]",0.492787,0.492763,0.124203,0.121591,False,False,False,False,True,False,False,True,False,False
2,4521474530,0,15,0,0,7,4,1,0,0,6.4,16221,46,-1172,-1033,18.6,1611.3,15,3,11,14,0,0,0,6.8,17254,28,20.3,1728.5,"[421, 84, 236, 43, 45]","[145, 154, 92, 134, 223]",0.489751,0.498580,0.086608,0.112683,False,False,False,False,False,True,False,False,False,False
3,4524384067,0,43,1,0,4,5,0,1,0,7.0,17954,55,-1321,-7,20.1,1515.7,15,2,5,10,0,0,0,7.0,17961,47,23.5,1647.8,"[64, 134, 516, 432, 429]","[110, 412, 58, 245, 238]",0.501475,0.508625,0.162425,0.144974,False,False,False,False,False,False,False,False,False,False
4,4436033771,0,75,4,0,6,6,0,0,0,7.0,18543,57,-1004,230,21.0,1640.0,17,2,6,7,1,0,0,7.0,18313,67,22.5,1740.4,"[101, 266, 245, 143, 21]","[51, 86, 69, 235, 32]",0.494971,0.511632,0.122280,0.077761,False,False,False,False,False,False,False,False,False,False

In [19]:
df_2.head()

,gameId,blueChampions,blueWins,blueFirstBlood,blueFirstBloodAssist,blueTotalGold,blueTotalExperience,blueTotalCS,blueGoldDiff,blueExperienceDiff,blueCSDiff,blueKills,blueAssists,blueDeaths,redChampions,redFirstBloodAssist,redTotalGold,redTotalExperience,redTotalCS,redAssists
0,ESPORTSTMNT03/1632489,"['Mordekaiser', 'Graves', 'Zoe', 'Miss Fortune...",1,1.0,0.0,16291.0,20459.0,382.0,1793.0,2365.0,65.0,1.0,0.0,0.0,"['Ornn', 'Kindred', 'Orianna', 'Ezreal', 'Leona']",0.0,14498.0,18094.0,317.0,0.0
1,ESPORTSTMNT03/1632500,"['Gragas', 'Graves', 'Rumble', ""Kai'Sa"", 'Alis...",0,1.0,0.0,15623.0,19210.0,340.0,759.0,171.0,-8.0,1.0,3.0,0.0,"['Ornn', 'Olaf', 'Syndra', 'Miss Fortune', 'Ga...",0.0,14864.0,19039.0,348.0,0.0
2,ESPORTSTMNT03/1632502,"['Gragas', 'Graves', 'Zoe', 'Yasuo', 'Alistar']",0,1.0,0.0,15043.0,16987.0,275.0,73.0,-1.0,-24.0,3.0,3.0,2.0,"['Rumble', 'Nidalee', 'Yone', 'Miss Fortune', ...",0.0,14970.0,16988.0,299.0,4.0
3,6909-9183,"['Karma', 'Pantheon', 'Syndra', 'Samira', 'Leo...",0,1.0,0.0,16177.0,19640.0,380.0,732.0,75.0,20.0,1.0,1.0,0.0,"['Aatrox', 'Nidalee', 'Viktor', ""Kai'Sa"", 'Gal...",0.0,15445.0,19565.0,360.0,0.0
4,6909-9184,"['Jax', 'Hecarim', 'Orianna', 'Samira', 'Alist...",0,0.0,0.0,16752.0,20020.0,361.0,1502.0,1164.0,40.0,2.0,2.0,1.0,"['Camille', 'Lillia', 'Viktor', ""Kai'Sa"", 'Mao...",0.0,15250.0,18856.0,321.0,1.0

In [20]:
from sklearn.model_selection import train_test_split as tts
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [29]:
df_2["blueCSPerMin"], df_2["redCSPerMin"] = df_2["blueTotalCS"]/10, df_2["redTotalCS"]/10
df_2["blueGoldPerMin"], df_2["redGoldPerMin"] = df_2["blueTotalGold"]/10, df_2["redTotalGold"]/10
df_2 = df_2.drop(["blueTotalCS", "redTotalCS", "blueTotalGold", "redTotalGold"], axis = 1)

In [30]:
pd.concat([df_2, df_1], axis = 0)

,gameId,blueChampions,blueWins,blueFirstBlood,blueFirstBloodAssist,blueTotalExperience,blueGoldDiff,blueExperienceDiff,blueCSDiff,blueKills,blueAssists,blueDeaths,redChampions,redFirstBloodAssist,redTotalExperience,redAssists,blueCSPerMin,redCSPerMin,blueGoldPerMin,redGoldPerMin,blueWardsPlaced,blueWardsDestroyed,blueDragons,blueHeralds,blueTowersDestroyed,blueAvgLevel,blueTotalJungleMinionsKilled,redWardsPlaced,redWardsDestroyed,redDragons,redHeralds,redTowersDestroyed,redAvgLevel,redTotalJungleMinionsKilled,bluePredWinrate,redPredWinrate,blueAvgPickrate,redAvgPickrate,blueHasWukong,redHasWukong,blueHasNautilus,redHasNautilus,blueHasKaiSa,redHasKaisa,blueHasIrelia,redHasIrelia,blueHasSylas,redHasSylas
0,ESPORTSTMNT03/1632489,"['Mordekaiser', 'Graves', 'Zoe', 'Miss Fortune...",1,1.0,0.0,20459.0,1793.0,2365.0,65.0,1.0,0.0,0.0,"['Ornn', 'Kindred', 'Orianna', 'Ezreal', 'Leona']",0.0,18094.0,0.0,38.2,31.7,1629.1,1449.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ESPORTSTMNT03/1632500,"['Gragas', 'Graves', 'Rumble', ""Kai'Sa"", 'Alis...",0,1.0,0.0,19210.0,759.0,171.0,-8.0,1.0,3.0,0.0,"['Ornn', 'Olaf', 'Syndra', 'Miss Fortune', 'Ga...",0.0,19039.0,0.0,34.0,34.8,1562.3,1486.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ESPORTSTMNT03/1632502,"['Gragas', 'Graves', 'Zoe', 'Yasuo', 'Alistar']",0,1.0,0.0,16987.0,73.0,-1.0,-24.0,3.0,3.0,2.0,"['Rumble', 'Nidalee', 'Yone', 'Miss Fortune', ...",0.0,16988.0,4.0,27.5,29.9,1504.3,1497.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6909-9183,"['Karma', 'Pantheon', 'Syndra', 'Samira', 'Leo...",0,1.0,0.0,19640.0,732.0,75.0,20.0,1.0,1.0,0.0,"['Aatrox', 'Nidalee', 'Viktor', ""Kai'Sa"", 'Gal...",0.0,19565.0,0.0,38.0,36.0,1617.7,1544.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6909-9184,"['Jax', 'Hecarim', 'Orianna', 'Samira', 'Alist...",0,0.0,0.0,20020.0,1502.0,1164.0,40.0,2.0,2.0,1.0,"['Camille', 'Lillia', 'Viktor', ""Kai'Sa"", 'Mao...",0.0,18856.0,1.0,36.1,32.1,1675.2,1525.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9874,4527873286,"[21, 26, 104, 122, 43]",1,1.0,NaN,18967.0,2519.0,2469.0,NaN,7.0,5.0,4.0,"[40, 81, 38, 517, 98]",NaN,16498.0,7.0,21.1,22.9,1776.5,1524.6,17.0,2.0,1.0,0.0,0.0,7.2,69.0,46.0,3.0,0.0,0.0,0.0,6.8,34.0,0.502941,0.500477,0.110720,0.134771,False,False,False,False,False,False,False,False,False,True
9875,4527797466,"[432, 110, 420, 48, 45]",1,0.0,NaN,19255.0,782.0,888.0,NaN,6.0,8.0,4.0,"[59, 61, 114, 235, 58]",NaN,18367.0,3.0,23.3,20.6,1623.8,1545.6,54.0,0.0,1.0,0.0,0.0,7.2,48.0,12.0,21.0,0.0,0.0,0.0,7.0,56.0,0.502162,0.502697,0.077639,0.102116,False,False,False,False,False,False,False,False,False,False
9876,4527713716,"[145, 62, 555, 268, 427]",0,0.0,NaN,18032.0,-2416.0,-1877.0,NaN,6.0,5.0,7.0,"[14, 26, 69, 102, 110]",NaN,19909.0,11.0,21.0,26.1,1590.3,1831.9,23.0,1.0,0.0,0.0,0.0,7.0,45.0,14.0,0.0,1.0,0.0,0.0,7.4,60.0,0.484159,0.503327,0.098674,0.075311,True,False,False,False,True,False,False,False,False,False
9877,4527628313,"[38, 24, 20, 412, 18]",0,1.0,NaN,17229.0,-839.0,-1085.0,NaN,2.0,3.0,3.0,"[98, 429, 421, 16, 39]",NaN,18314.0,1.0,22.4,24.7,1445.9,1529.8,14.0,4.0,1.0,0.0,0.0,6.6,48.0,66.0,4.0,0.0,0.0,0.0,7.2,40.0,0.512919,0.488982,0.105011,0.102359,False,False,False,False,False,False,False,True,False,False
9878,4523772935,"[517, 267, 145, 238, 20]",1,1.0,NaN,17321.0,927.0,-58.0,NaN,6.0,5.0,6.0,"[64, 18, 134, 555, 1]",NaN,17379.0,4.0,20.7,20.1,1626.6,1533.9,18.0,0.0,0.0,0.0,0.0,7.0,44.0,9.0,2.0,1.0,0.0,0.0,6.8,46.0,0.500558,0.487695,0.097945,0.119911,False,False,False,False,True,False,False,False,True,False

In [40]:
import pickle

waifu = pickle.load(open("../../../Pickles/WaifuDictionary.pkl", "rb"))

In [ ]:
df_blueChampions, df_redChampions = df_1["blueChampions"], df_1["redChampions"]