In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('../../../archive/high_diamond_ranked_10min.csv')

In [14]:
df.head(8)

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueAssists,blueEliteMonsters,blueDragons,blueHeralds,blueTowersDestroyed,blueAvgLevel,blueTotalExperience,blueTotalJungleMinionsKilled,blueGoldDiff,blueExperienceDiff,blueCSPerMin,blueGoldPerMin,redWardsPlaced,redWardsDestroyed,redKills,redAssists,redEliteMonsters,redDragons,redHeralds,redTowersDestroyed,redAvgLevel,redTotalExperience,redTotalJungleMinionsKilled,redCSPerMin,redGoldPerMin
0,4519157822,0,28,2,1,9,11,0,0,0,0,6.6,17039,36,643,-8,19.5,1721.0,15,6,6,8,0,0,0,0,6.8,17047,55,19.7,1656.7
1,4523371949,0,12,1,0,5,5,0,0,0,0,6.6,16265,43,-2908,-1173,17.4,1471.2,12,1,5,2,2,1,1,1,6.8,17438,52,24.0,1762.0
2,4521474530,0,15,0,0,7,4,1,1,0,0,6.4,16221,46,-1172,-1033,18.6,1611.3,15,3,11,14,0,0,0,0,6.8,17254,28,20.3,1728.5
3,4524384067,0,43,1,0,4,5,1,0,1,0,7.0,17954,55,-1321,-7,20.1,1515.7,15,2,5,10,0,0,0,0,7.0,17961,47,23.5,1647.8
4,4436033771,0,75,4,0,6,6,0,0,0,0,7.0,18543,57,-1004,230,21.0,1640.0,17,2,6,7,1,1,0,0,7.0,18313,67,22.5,1740.4
5,4475365709,1,18,0,0,5,6,1,1,0,0,7.0,18161,42,698,101,22.5,1589.9,36,5,3,2,0,0,0,0,7.0,18060,59,22.1,1520.1
6,4493010632,1,18,3,1,7,7,1,1,0,0,6.8,16967,53,2411,1563,22.5,1687.4,57,1,6,9,0,0,0,0,6.4,15404,35,16.4,1446.3
7,4496759358,0,16,2,0,5,3,0,0,0,0,6.4,16138,48,-2615,-800,20.9,1530.5,15,0,13,11,1,1,0,0,6.6,16938,54,15.7,1792.0

In [4]:
df.columns

Index(['gameId', 'blueWins', 'blueWardsPlaced', 'blueWardsDestroyed',
       'blueFirstBlood', 'blueKills', 'blueDeaths', 'blueAssists',
       'blueEliteMonsters', 'blueDragons', 'blueHeralds',
       'blueTowersDestroyed', 'blueTotalGold', 'blueAvgLevel',
       'blueTotalExperience', 'blueTotalMinionsKilled',
       'blueTotalJungleMinionsKilled', 'blueGoldDiff', 'blueExperienceDiff',
       'blueCSPerMin', 'blueGoldPerMin', 'redWardsPlaced', 'redWardsDestroyed',
       'redFirstBlood', 'redKills', 'redDeaths', 'redAssists',
       'redEliteMonsters', 'redDragons', 'redHeralds', 'redTowersDestroyed',
       'redTotalGold', 'redAvgLevel', 'redTotalExperience',
       'redTotalMinionsKilled', 'redTotalJungleMinionsKilled', 'redGoldDiff',
       'redExperienceDiff', 'redCSPerMin', 'redGoldPerMin'],
      dtype='object')

In [5]:
df.drop(['blueDeaths','redDeaths','blueTotalGold','redTotalGold','redGoldDiff','redExperienceDiff',
        'redFirstBlood','blueTotalMinionsKilled','redTotalMinionsKilled'], axis = 1, inplace = True)
correlations = df.corr().stack().reset_index()

In [6]:
correlations['pair'] = correlations['level_0']+'|'+correlations['level_1']
correlations['pair'] = correlations['pair'].map(lambda x: sorted(x.split('|')))
correlations = correlations.loc[correlations['pair'].map(lambda x: len(set(x))) != 1]
correlations['pair'] = correlations['pair'].map(lambda x: ', '.join(x))

In [7]:
correlations.drop(['level_0','level_1'], axis = 1, inplace = True)
correlations.drop_duplicates(inplace = True)

In [8]:
correlations[0] = abs(correlations[0])
correlations.set_index('pair', inplace = True)

In [9]:
correlations.sort_values(by = 0, inplace = True)

In [10]:
correlations.loc[correlations[0] >= 0.75]

                                                0
pair
blueDragons, blueEliteMonsters           0.781039
blueExperienceDiff, redTotalExperience   0.800089
blueExperienceDiff, blueTotalExperience  0.800815
redAssists, redKills                     0.804023
blueGoldDiff, redGoldPerMin              0.804347
redDragons, redEliteMonsters             0.811234
blueAssists, blueKills                   0.813667
blueGoldDiff, blueGoldPerMin             0.816803
redGoldPerMin, redKills                  0.885728
blueGoldPerMin, blueKills                0.888751
blueExperienceDiff, blueGoldDiff         0.894729
blueAvgLevel, blueTotalExperience        0.901297
redAvgLevel, redTotalExperience          0.901748

In [11]:
len(df.columns)

31

In [12]:
df.to_csv(path_or_buf = '../../../archive/high_diamond_ranked_10min_no_identical.csv')

In [13]:
len(df)

9879