In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("raw_data/2021_LoL_esports_match_data_from_OraclesElixir_20210713.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99336 entries, 0 to 99335
Columns: 117 entries, gameid to opp_deathsat15
dtypes: float64(81), int64(20), object(16)
memory usage: 88.7+ MB

In [4]:
df.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,ESPORTSTMNT03/1632489,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2021,NaN,0,2021-01-02 07:40:39,1,10.25,...,118.0,748.0,-56.0,-4.0,2.0,0.0,1.0,0.0,1.0,1.0
1,ESPORTSTMNT03/1632489,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2021,NaN,0,2021-01-02 07:40:39,1,10.25,...,84.0,2120.0,3405.0,62.0,3.0,2.0,0.0,2.0,0.0,3.0
2,ESPORTSTMNT03/1632489,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2021,NaN,0,2021-01-02 07:40:39,1,10.25,...,143.0,1578.0,354.0,15.0,2.0,3.0,0.0,0.0,0.0,0.0
3,ESPORTSTMNT03/1632489,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2021,NaN,0,2021-01-02 07:40:39,1,10.25,...,120.0,124.0,102.0,10.0,0.0,4.0,2.0,1.0,1.0,2.0
4,ESPORTSTMNT03/1632489,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2021,NaN,0,2021-01-02 07:40:39,1,10.25,...,25.0,448.0,450.0,3.0,1.0,4.0,0.0,0.0,2.0,2.0

In [5]:
df["league"].value_counts()

LDL        13236
LPL         6444
LCK         4296
RCL         3984
LMF         3528
OTBLX       3264
LHE         3216
LCS         3036
LCS.A       2940
CU          2448
UPL         2376
NLC         2220
LEC         2136
VCS         2112
SL          2100
PRM         2064
CBLOL       2040
CBLOL.A     1956
TCL         1944
LCK CL      1932
LFL         1932
PGN         1860
GLL         1860
TRA         1848
BIG         1776
PCS         1752
HM          1632
UKLC        1596
EM          1536
HC          1452
UL          1452
LCO         1380
LJL         1344
LLA         1344
LPLOL       1332
EBL         1260
LCL         1116
MSI          972
BL           876
DL           816
BM           780
GSG          636
UGP          528
NERD         504
AOL          444
KeSPA         36
Name: league, dtype: int64

In [6]:
lcs_df = df[df.league == "LCS"]

In [9]:
lcs_df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3036 entries, 2448 to 98867
Data columns (total 117 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    3036 non-null   object
 1   datacompleteness          3036 non-null   object
 2   url                       3036 non-null   object
 3   league                    3036 non-null   object
 4   year                      3036 non-null   int64
 5   split                     3036 non-null   object
 6   playoffs                  3036 non-null   int64
 7   date                      3036 non-null   object
 8   game                      3036 non-null   int64
 9   patch                     3036 non-null   float64
 10  playerid                  3036 non-null   int64
 11  side                      3036 non-null   object
 12  position                  3036 non-null   object
 13  player                    2530 non-null   object
 14  team                      3036 non-null   object
 15  champion                  2530 non-null   object
 16  ban1                      3036 non-null   object
 17  ban2                      3030 non-null   object
 18  ban3                      3030 non-null   object
 19  ban4                      3036 non-null   object
 20  ban5                      3018 non-null   object
 21  gamelength                3036 non-null   int64
 22  result                    3036 non-null   int64
 23  kills                     3036 non-null   int64
 24  deaths                    3036 non-null   int64
 25  assists                   3036 non-null   int64
 26  teamkills                 3036 non-null   int64
 27  teamdeaths                3036 non-null   int64
 28  doublekills               3036 non-null   float64
 29  triplekills               3036 non-null   float64
 30  quadrakills               3036 non-null   float64
 31  pentakills                3036 non-null   float64
 32  firstblood                3036 non-null   float64
 33  firstbloodkill            2530 non-null   float64
 34  firstbloodassist          2530 non-null   float64
 35  firstbloodvictim          2530 non-null   float64
 36  team kpm                  3036 non-null   float64
 37  ckpm                      3036 non-null   float64
 38  firstdragon               506 non-null    float64
 39  dragons                   506 non-null    float64
 40  opp_dragons               506 non-null    float64
 41  elementaldrakes           506 non-null    float64
 42  opp_elementaldrakes       506 non-null    float64
 43  infernals                 506 non-null    float64
 44  mountains                 506 non-null    float64
 45  clouds                    506 non-null    float64
 46  oceans                    506 non-null    float64
 47  dragons (type unknown)    0 non-null      float64
 48  elders                    506 non-null    float64
 49  opp_elders                506 non-null    float64
 50  firstherald               506 non-null    float64
 51  heralds                   506 non-null    float64
 52  opp_heralds               506 non-null    float64
 53  firstbaron                506 non-null    float64
 54  barons                    506 non-null    float64
 55  opp_barons                506 non-null    float64
 56  firsttower                506 non-null    float64
 57  towers                    506 non-null    float64
 58  opp_towers                506 non-null    float64
 59  firstmidtower             506 non-null    float64
 60  firsttothreetowers        506 non-null    float64
 61  inhibitors                3036 non-null   float64
 62  opp_inhibitors            3036 non-null   float64
 63  damagetochampions         3036 non-null   int64
 64  dpm                       3036 non-null   float64
 65  damageshare               2530 non-null   float64
 66  damagetakenperminute      3036 non-null   float64
 67  damagemitigatedperminute  3036 non-null   float64
 68  wardsplaced               3036 non-null   int64
 69  wpm                       3036 non-null   float64
 70  wardskilled               3036 non-null   int64
 71  wcpm                      3036 non-null   float64
 72  controlwardsbought        3036 non-null   int64
 73  visionscore               3036 non-null   float64
 74  vspm                      3036 non-null   float64
 75  totalgold                 3036 non-null   int64
 76  earnedgold                3036 non-null   int64
 77  earned gpm                3036 non-null   float64
 78  earnedgoldshare           2530 non-null   float64
 79  goldspent                 3036 non-null   float64
 80  gspd                      506 non-null    float64
 81  total cs                  2530 non-null   float64
 82  minionkills               3036 non-null   float64
 83  monsterkills              3036 non-null   int64
 84  monsterkillsownjungle     3036 non-null   int64
 85  monsterkillsenemyjungle   3036 non-null   int64
 86  cspm                      3036 non-null   float64
 87  goldat10                  3036 non-null   float64
 88  xpat10                    3036 non-null   float64
 89  csat10                    3036 non-null   float64
 90  opp_goldat10              3036 non-null   float64
 91  opp_xpat10                3036 non-null   float64
 92  opp_csat10                3036 non-null   float64
 93  golddiffat10              3036 non-null   float64
 94  xpdiffat10                3036 non-null   float64
 95  csdiffat10                3036 non-null   float64
 96  killsat10                 3036 non-null   float64
 97  assistsat10               3036 non-null   float64
 98  deathsat10                3036 non-null   float64
 99  opp_killsat10             3036 non-null   float64
 100 opp_assistsat10           3036 non-null   float64
 101 opp_deathsat10            3036 non-null   float64
 102 goldat15                  3036 non-null   float64
 103 xpat15                    3036 non-null   float64
 104 csat15                    3036 non-null   float64
 105 opp_goldat15              3036 non-null   float64
 106 opp_xpat15                3036 non-null   float64
 107 opp_csat15                3036 non-null   float64
 108 golddiffat15              3036 non-null   float64
 109 xpdiffat15                3036 non-null   float64
 110 csdiffat15                3036 non-null   float64
 111 killsat15                 3036 non-null   float64
 112 assistsat15               3036 non-null   float64
 113 deathsat15                3036 non-null   float64
 114 opp_killsat15             3036 non-null   float64
 115 opp_assistsat15           3036 non-null   float64
 116 opp_deathsat15            3036 non-null   float64
dtypes: float64(81), int64(20), object(16)
memory usage: 2.7+ MB

In [10]:
# Going to create a dataframe for match stats by team
# overall I'm going to ignore information relating to champions (picks, bans, etc.)
# I'm going to first focus on gold, experience, and objective stats
# After that kills and vision stats

In [13]:
# first, i'm going to export this lcs dataframe into the data folder for user later or in other notebooks

lcs_df.to_csv("data/lcs_2021_match_data_OraclesElixir_20210713.csv", index = False)